server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ural-aggregator
    version: @project.version@
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

security:
  jwt:
    custom-decoder: false

proxy:
  cargo:
    url: ${PROXY_CARGO_URL}
  users:
    url: ${PROXY_USERS_URL}
  auth:
    url: ${PROXY_AUTH_URL}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
    org:
      springframework: INFO
      hibernate: INFO
      apache:
        tomcat:
          util: WARN
