server:
  port: 10902

spring:
  application:
    name: ural-cargo
    version: @project.version@

logging:
  level:
    root: info
    org:
      springframework: INFO
      hibernate: INFO
      apache:
        tomcat:
          util: WARN
